emulator -avd Pixel_6_API_31 -writable-system \
        -no-window  \
        -verbose \
        -show-kernel \
        -no-cache \
        -no-snapstorage \
        -no-snapshot-save \
        -no-snapshot-load \
        -no-audio \
        -no-snapshot \
        -wipe-data \
        -accel on -netdelay none -no-sim